### ISSUE TITLE
ServiceNotFoundException on "sonata.admin.route.path_info_slashes"

### ISSUE THREAD

**Issue by Bendihossan** [symfony-cmf/SimpleCmsBundle#6]
I get the following on install:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                          
  The service "symfony_cmf_simple_cms.admin.page" has a dependency on a non-existent service "sonata.admin.route.path_info_slashes".  
```

My composer.json: 

``` json
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.1.*",
        "doctrine/orm": ">=2.2.3,<2.4-dev",
        "doctrine/doctrine-bundle": "dev-master",
        "twig/extensions": "dev-master",
        "symfony/assetic-bundle": "dev-master",
        "symfony/swiftmailer-bundle": "dev-master",
        "symfony/monolog-bundle": "dev-master",
        "sensio/distribution-bundle": "dev-master",
        "sensio/framework-extra-bundle": "dev-master",
        "sensio/generator-bundle": "dev-master",
        "jms/security-extra-bundle": "1.2.*",
        "jms/di-extra-bundle": "1.1.x-dev",
        "symfony-cmf/core-bundle": "dev-master",
        "symfony-cmf/simple-cms-bundle": "dev-master",
        "symfony-cmf/routing-extra-bundle": "dev-master",
        "symfony-cmf/menu-bundle": "dev-master",
        "symfony-cmf/multilang-content-bundle": "dev-master",
        "sonata-project/block-bundle": "dev-master",
        "sonata-project/admin-bundle": "dev-master"
    },
```

``` yaml
#app/config/config.yml 
symfony_cmf_menu:
    document_manager_name: default

symfony_cmf_routing_extra:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            symfony_cmf_routing_extra.dynamic_router: 200
            # enable the symfony default router with a lower priority
            router.default: 100
        # whether the chain router should replace the default router. defaults to true
        # if you set this to false, the router is just available as service
        # symfony_cmf_routing_extra.router and you  need to do somthing to trigger it
        # replace_symfony_router: true
    dynamic:
        enabled: true
        generic_controller: symfony_cmf_content.controller:indexAction
        controllers_by_alias:
            editablestatic: sandbox_main.controller:indexAction
        controllers_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: symfony_cmf_content.controller::indexAction
        templates_by_class:
            Symfony\Cmf\Bundle\ContentBundle\Document\StaticContent: SymfonyCmfContentBundle:StaticContent:index.html.twig

        # the repository is responsible to load routes
        # for phpcr-odm, we mainly use this because it can map from url to repository path
        # an orm repository might need different logic. look at cmf_routing.xml for an example if you
        # need to define your own service
        manager_registry: doctrine_phpcr
        manager_name: default

        # if you use the default doctrine route repository servie, you can use this to customize
        # the root path for the phpcr-odm RouteRepository
        # this base path will be injected by the Listener\IdPrefix - but only to routes
        # matching the prefix, to allow for more than one route source.
        routing_repositoryroot: /cms/routes

symfony_cmf_simple_cms:
    routing:
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Document\Page:    SymfonyCmfSimpleCmsBundle:Page:index.html.twig

sonata_block:
        default_contexts: [cms]
        blocks:
            sonata.admin.block.admin_list:
                contexts: [admin]

            sonata.block.service.text:
            sonata.block.service.action:
            sonata.block.service.rss:
```

This also happens if I do not use the Sonata Admin bundle:

``` yaml
#app/config/config.yml
symfony_cmf_simple_cms:
    use_sonata_admin: false
```

These are the references I can find to "sonata.admin.route.path_info_slashes" in the vendors

``` bash
grep -r "sonata.admin.route.path_info_slashes" vendor/*
vendor/symfony-cmf/simple-cms-bundle/Symfony/Cmf/Bundle/SimpleCmsBundle/Resources/config/services/admin.xml:                <argument type="service" id="sonata.admin.route.path_info_slashes"/>
vendor/symfony-cmf/menu-bundle/Symfony/Cmf/Bundle/MenuBundle/Resources/config/menu-admin.xml:                <argument type="service" id="sonata.admin.route.path_info_slashes" />

```
